package org.antlr.v4.semantics;

/**  check for the following errors:
 *
 * RULE_REDEFINITION
RULE_HAS_NO_ARGS
UNDEFINED_RULE_REF
MISSING_RULE_ARGS
SYMBOL_CONFLICTS_WITH_GLOBAL_SCOPE
LABEL_CONFLICTS_WITH_RULE
LABEL_CONFLICTS_WITH_TOKEN
LABEL_TYPE_CONFLICT
ACTION_REDEFINITION
NO_SUCH_RULE_IN_SCOPE
TOKEN_ALIAS_CONFLICT
TOKEN_ALIAS_REASSIGNMENT

 The
*/
public class SymbolCollisionChecks {
}
