version: '4.9.2-SNAPSHOT+AppVeyor.{build}'
cache:
  - '%USERPROFILE%\.m2'
  - '%USERPROFILE%\.nuget\packages -> **\project.json'
image: Visual Studio 2019
build: off
install:
  - mv antlr-php-runtime runtime/PHP
build_script:
  - mvn -DskipTests install --batch-mode
test_script:
  - mvn -Dtest=java.* install --batch-mode
artifacts:
- path: 'runtime\**\*.nupkg'
  name: NuGet
