version: '4.9.2-SNAPSHOT+AppVeyor.{build}'
cache:
  - '%USERPROFILE%\.m2'
  - '%USERPROFILE%\.nuget\packages -> **\project.json'
image: Visual Studio 2019
build: off
install:
  - git clone https://github.com/antlr/antlr-php-runtime.git
  - mv antlr-php-runtime runtime/PHP
  - cinst -y php --params "/InstallDir:C:\tools\php"
  - cinst -y composer
build_script:
  - mvn -DskipTests install --batch-mode
test_script:
  - cd runtime-testsuite
  - mvn -Dtest=php.* test -Dantlr-php-php="C:\tools\php\php.exe" --batch-mode
