version: '4.9.2-SNAPSHOT+AppVeyor.{build}'
cache:
  - '%USERPROFILE%\.m2'
  - '%USERPROFILE%\.nuget\packages -> **\project.json'
image: Visual Studio 2019
build: off
build_script:
  - mvn -DskipTests install --batch-mode
  - dotnet build runtime/CSharp/src/Antlr4.csproj -c Release
after_build:
  - dotnet pack runtime/CSharp/src/Antlr4.csproj -c Release
test_script:
  - cd runtime-testsuite
  - mvn -Dtest=python2.* test
artifacts:
- path: 'runtime\**\*.nupkg'
  name: NuGet
