env:
  browser: false
  node: true
  es2016: true
  amd: true
  jasmine: true
extends:
  - eslint:recommended
  - plugin:@typescript-eslint/recommended
  - plugin:@typescript-eslint/recommended-requiring-type-checking
globals:
  Atomics: readonly
  SharedArrayBuffer: readonly
  Set: readonly
parser: "@typescript-eslint/parser"
parserOptions:
  sourceType: module
  project: ['./tsconfig.json']
plugins:
  - "@typescript-eslint"
rules:
  no-unused-vars: ["error", {vars: "all", args: "none"}]
  no-prototype-builtins: [ "off" ]
  no-fallthrough: ["error", { "commentPattern": "no-break" }]
