env:
  browser: true
  node: true
  es2016: true
  amd: true
  jasmine: true
extends:
  - eslint:recommended
globals:
  Atomics: readonly
  SharedArrayBuffer: readonly
  Set: readonly
parser: "@babel/eslint-parser"
parserOptions:
  sourceType: module
  project: ['./tsconfig.json']
  ecmaVersion: 2022
rules:
  no-unused-vars:
    - error
    - vars: all
      args: none
  no-prototype-builtins:
    - off
  no-fallthrough:
    - error
    - commentPattern: no-break
  quotes:
    - error
    - single
  object-curly-spacing:
    - error
    - always
  semi:
    - error
    - always
  indent:
    - error
    - 4
  comma-dangle:
    - error
    - only-multiline
overrides:
  - files:
      - "*.ts"
    extends:
      - eslint:recommended
      - plugin:@typescript-eslint/eslint-recommended
    parser: "@typescript-eslint/parser"
    plugins:
      - "@typescript-eslint"
