name: Swift/MacOSX

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:
    runs-on: [self-hosted, macOS, x64]
    strategy:
      fail-fast: false
      matrix:
        include:
          - GROUP: LEXER
          - GROUP: PARSER
          - GROUP: RECURSION
    steps:
    - uses: actions/checkout@v2
    - name: Set up JDK 1.8
      uses: actions/setup-java@v1
      with:
        java-version: 1.8
    - name: Set up Maven
      uses: stCarolas/setup-maven@v4
      with:
        maven-version: 3.5.4    
    - name: Build tool with Maven
      run: mvn install -DskipTests=true -Dmaven.javadoc.skip=true -B -V
    - name: Test with Maven
      run: arch -x86_64 .github/scripts/run-tests-swift.sh
      env: 
        TARGET: swift
        GROUP: ${{ matrix.GROUP }}
